#!/usr/bin/env bash
# Downloads all Fluent 3D emoji icons used in Gainbase into assets/icons3d/
# Each file is saved as assets/icons3d/<id>.png matching the CATEGORY_3D_ICONS_LIST id

set -e

BASE="https://raw.githubusercontent.com/microsoft/fluentui-emoji/main/assets"
OUT="$(dirname "$0")/../assets/icons3d"
mkdir -p "$OUT"

download() {
  local id="$1"
  local path="$2"
  local dest="$OUT/${id}.png"
  if [ -f "$dest" ]; then
    echo "  ✓ Already exists: ${id}.png"
    return
  fi
  echo "  ↓ Downloading ${id}.png ..."
  curl -fsSL "${BASE}/${path}" -o "$dest" || echo "  ✗ FAILED: ${id} (${path})"
}

echo "🚀 Downloading Gainbase 3D icons to assets/icons3d/ ..."

# ── CATEGORY_3D_ICONS_LIST ───────────────────────────────────────────────────
download "food"           "Steaming%20bowl/3D/steaming_bowl_3d.png"
download "grocery"        "Shopping%20bags/3D/shopping_bags_3d.png"
download "beverage"       "Tropical%20drink/3D/tropical_drink_3d.png"
download "coffee"         "Hot%20beverage/3D/hot_beverage_3d.png"
download "pizza"          "Pizza/3D/pizza_3d.png"
download "burger"         "Hamburger/3D/hamburger_3d.png"
download "cake"           "Birthday%20cake/3D/birthday_cake_3d.png"
download "cookie"         "Cookie/3D/cookie_3d.png"
download "broccoli"       "Broccoli/3D/broccoli_3d.png"
download "carrot"         "Carrot/3D/carrot_3d.png"
download "apple"          "Red%20apple/3D/red_apple_3d.png"
download "house"          "House/3D/house_3d.png"
download "home_garden"    "House%20with%20garden/3D/house_with_garden_3d.png"
download "electric"       "Light%20bulb/3D/light_bulb_3d.png"
download "water"          "Droplet/3D/droplet_3d.png"
download "gas"            "Fire/3D/fire_3d.png"
download "internet"       "Satellite%20antenna/3D/satellite_antenna_3d.png"
download "wrench"         "Wrench/3D/wrench_3d.png"
download "hammer"         "Hammer/3D/hammer_3d.png"
download "key"            "Key/3D/key_3d.png"
download "holiday"        "Beach%20with%20umbrella/3D/beach_with_umbrella_3d.png"
download "travel"         "Airplane/3D/airplane_3d.png"
download "car"            "Automobile/3D/automobile_3d.png"
download "fuel"           "Fuel%20pump/3D/fuel_pump_3d.png"
download "bus"            "Bus/3D/bus_3d.png"
download "luggage"        "Luggage/3D/luggage_3d.png"
download "compass"        "Compass/3D/compass_3d.png"
download "gym"            "Running%20shoe/3D/running_shoe_3d.png"
download "fitness"        "Boxing%20glove/3D/boxing_glove_3d.png"
download "biceps"         "Flexed%20biceps/Default/3D/flexed_biceps_3d_default.png"
download "medical"        "Pill/3D/pill_3d.png"
download "trophy"         "Trophy/3D/trophy_3d.png"
download "medal"          "Sports%20medal/3D/sports_medal_3d.png"
download "heart"          "Heart%20with%20ribbon/3D/heart_with_ribbon_3d.png"
download "shopping"       "Shopping%20bags/3D/shopping_bags_3d.png"
download "clothes"        "T-shirt/3D/t-shirt_3d.png"
download "gift"           "Wrapped%20gift/3D/wrapped_gift_3d.png"
download "sparkles"       "Sparkles/3D/sparkles_3d.png"
download "crown"          "Crown/3D/crown_3d.png"
download "gem"            "Gem%20stone/3D/gem_stone_3d.png"
download "package"        "Package/3D/package_3d.png"
download "laptop"         "Laptop/3D/laptop_3d.png"
download "phone"          "Mobile%20phone/3D/mobile_phone_3d.png"
download "cloud"          "Cloud/3D/cloud_3d.png"
download "shield"         "Shield/3D/shield_3d.png"
download "bell"           "Bell/3D/bell_3d.png"
download "books"          "Books/3D/books_3d.png"
download "education"      "Graduation%20cap/3D/graduation_cap_3d.png"
download "briefcase"      "Briefcase/3D/briefcase_3d.png"
download "headphones"     "Headphone/3D/headphone_3d.png"
download "musical_notes"  "Musical%20notes/3D/musical_notes_3d.png"
download "popcorn"        "Popcorn/3D/popcorn_3d.png"
download "tv"             "Television/3D/television_3d.png"
download "clapperboard"   "Clapper%20board/3D/clapper_board_3d.png"
download "film_projector" "Film%20projector/3D/film_projector_3d.png"
download "video_game"     "Video%20game/3D/video_game_3d.png"
download "guitar"         "Guitar/3D/guitar_3d.png"
download "microphone"     "Studio%20microphone/3D/studio_microphone_3d.png"
download "camera"         "Camera/3D/camera_3d.png"
download "newspaper"      "Newspaper/3D/newspaper_3d.png"
download "banknote"       "Dollar%20banknote/3D/dollar_banknote_3d.png"
download "money"          "Money%20bag/3D/money_bag_3d.png"
download "wallet"         "Purse/3D/purse_3d.png"
download "investments"    "Chart%20increasing/3D/chart_increasing_3d.png"
download "credit_card"    "Credit%20card/3D/credit_card_3d.png"
download "receipt"        "Receipt/3D/receipt_3d.png"
download "coin"           "Coin/3D/coin_3d.png"
download "transfer"       "Clockwise%20vertical%20arrows/3D/clockwise_vertical_arrows_3d.png"
download "target"         "Direct%20hit/3D/direct_hit_3d.png"
download "rocket"         "Rocket/3D/rocket_3d.png"
download "star"           "Glowing%20star/3D/glowing_star_3d.png"
download "fire"           "Fire/3D/fire_3d.png"
download "umbrella"       "Umbrella/3D/umbrella_3d.png"
download "lock"           "Locked/3D/locked_3d.png"

# ── Additional icons used only via FLUENT_3D_MAP (not in list) ───────────────
download "pot_of_food"    "Pot%20of%20food/3D/pot_of_food_3d.png"
download "users"          "People%20hugging/3D/people_hugging_3d.png"
download "loan"           "Money%20bag/3D/money_bag_3d.png"

echo ""
echo "✅ Done! $(ls "$OUT"/*.png 2>/dev/null | wc -l | tr -d ' ') icons saved to assets/icons3d/"
